# Define a docker compose yaml file that initializes the server and workers
version: '3.7'

services:
  ps0:
    build:
      context: .
    network_mode: "host"
    command:
      ["python3", "Distributed2.py", "--ps_hosts=localhost:2222", "--worker_hosts=localhost:2223,localhost:2224", "--job_name=ps", "--task_index=0"]

  # The first worker container
  worker0:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - "worker1"
    command:
      ["python3", "Distributed2.py", "--ps_hosts=localhost:2222", "--worker_hosts=localhost:2223,localhost:2224", "--job_name=worker", "--task_index=0"]

  # The second worker container
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - "ps0"
    command:
      ["python3", "Distributed2.py", "--ps_hosts=localhost:2222", "--worker_hosts=localhost:2223,localhost:2224", "--job_name=worker", "--task_index=1"]
