# The first 4 lines look very familiar
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workerdb-persistent-volume-claim

# The spec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
